using UnityEngine;

/// <summary>
/// Bagian Employee yang mengurus regenerasi mood otomatis jika mood kurang dari 3.
/// </summary>
public partial class Employee
{
    [Header("Mood Regeneration")]
    [SerializeField] private float moodRegenInterval = 60f; 
    private float moodRegenTimer;

    private void UpdateMoodRegen()
    {
        if (currentState == EmployeeState.Dead)
            return;

        if (mood < 3)
        {
            moodRegenTimer += Time.deltaTime;
            if (moodRegenTimer >= moodRegenInterval)
            {
                moodRegenTimer = 0f;
                ModifyMood(1);
                Debug.Log($"[{EmployeeName}] Mood regenerated by 1. Current mood: {mood}");
            }
        }
        else
        {
            moodRegenTimer = 0f;
        }
    }
}
